openapi: 3.0.0
info:
  title: Example API
  version: 3.0.0
paths: 
  /customers:
    post:
      tags:
        - Customers
      summary: Creates a new customer
      requestBody:
        required: true
        description: "test"
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
            example:
              $ref: '#/components/examples/CustomerInput'
              
        

      responses: 
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        401:
          $ref: '#/components/responses/Unauthorized'   # <-----
        404:
          $ref: '#/components/responses/NotFound' 
    get:
      tags:
        - Customers
      parameters:
        - $ref: '#/components/parameters/pageNumber'
        - $ref: '#/components/parameters/itemsPerPage'
      responses:
        200:
          description: OK
        401:
          $ref: '#/components/responses/Unauthorized'   # <-----
        404:
          $ref: '#/components/responses/NotFound' 

  /customers/{id}:
    get:
      tags:
        - Customers
      summary: Gets a customer by ID
      description: >
        A detailed description of the operation.
        Use markdown for rich text representation,
        such as **bold**, *italic*, and [links](https://swagger.io).
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
            format: int64    
      responses: 
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        401:
          $ref: '#/components/responses/Unauthorized'   # <-----
        404:
          $ref: '#/components/responses/NotFound'

components:

  schemas:
    

    Customer:
      type: object
      required:
        - title
        - firstName
        - lastName
        - dateOfBirth
        - email
        - phoneNumber
        - gender
        - citizenship
        - nationalInsuranceNumber
        - employmentStatus
        - address
      properties:
        id:
          type: string
          readOnly: true
        createdAt:
          $ref: '#/components/schemas/timestamp'
          readOnly: true
        updatedAt:
          $ref: '#/components/schemas/timestamp'
          readOnly: true
        deactivatedAt:
          $ref: '#/components/schemas/timestamp'
          readOnly: true
        penId:
          type: string
          readOnly: true
        email:
          type: string
        title:
          type: string
          enum:
            - Captain
            - Dr
            - Lady
            - Lieutenant
            - LieutenantCommander
            - Lord
            - Major
            - Master
            - Miss
            - Mr
            - Mrs
            - Ms
            - Mx
            - Professor
            - Reverend
            - Sir
            - WingCommander
        firstName:
          type: string
          example: "John"
        middleName:
          type: string
        lastName:
          type: string
          example: "Doe"
        phoneNumber:
          type: string
        dateOfBirth:
          $ref: '#/components/schemas/date'
        lastestValuation:
          type: integer
          readOnly: true
          format: int32
        memberDeclarationAcceptedAt:
          type: string
        employmentStatus:
          type: string
          enum:
            - CareOver16
            - CareUnder16s
            - Child
            - Education
            - Employed
            - Other
            - Retired
            - SelfEmployed
            - Unemployed
            - Director
        countryOfBirth:
          type: string
        citizenship:
          description: add valid countries here
          type: string
        gender:
          type: string
          enum:
            - Male
            - Female
        address:
          $ref: '#/components/schemas/Address'
        nationalInsuranceNumber:
          type: string
    TaxResidency:
      type: object
      required:
        - id
        - createdAt
        - updatedAt
        - currentYearResidencyStatus
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        user:
          $ref: '#/components/schemas/Customer'
        currentYearResidencyStatus:
          type: string
          enum:
            - ScotResident
            - OtherUKResident
        nextYearForecastResidencyStatus:
          type: string
          enum:
            - ScotResident
            - OtherUKResident
    Fund:
      type: object
      required:
        - id
        - createdAt
        - updatedAt
        - ISIN
        - secclId
        - name
        - description
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        externalName:
          type: string
        group:
          type: string
          enum:
            - Basic
            - Advanced
            - Impact
            - Sustainable
            - Shariah
        ISIN:
          type: string
        secclId:
          type: string
        factSheet:
          type: string
        name:
          type: string
        description:
          type: string
        equity:
          type: integer
          format: int32
    Company:
      type: object
      required:
        - id
        - ownershipVerified
      properties:
        id:
          type: string
        number:
          type: string
        companiesHouseData:
          type: string
        ownershipVerified:
          type: boolean
        companyCategory:
          type: string
        companySubCategory:
          type: string
    Address:
      type: object
      required:
        - id
        - line1
        - postcode
        - country
      properties:
        id:
          type: string
          readOnly: true
        streetNumber:
          type: string
        line1:
          type: string
        line2:
          type: string
        town:
          type: string
        county:
          type: string
        postcode:
          type: string
        country:
          type: string


    Transfer:
      type: object
      required:
        - id
        - createdAt
        - updatedAt
        - provider
        - policyNumber
        - estimatedAmount
        - previousStatuses
        - status
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        airtableId:
          type: string
        address:
          $ref: '#/components/schemas/Address'
        provider:
          type: string
        pensionProvider:
          $ref: '#/components/schemas/PensionProvider'
        policyNumber:
          type: string
        policyNumberRegexIgnored:
          type: boolean
        customerNumber:
          type: string
        estimatedValue:
          type: integer
          format: int32
        previousStatuses:
          type: array
          items:
            type: string
            enum:
              - Requested
              - NewTransfer
              - FundsSent
              - Complete
              - Cancelled
              - OnHold
              - SubmittedToOrigo
              - NeedsRequestingOnOrigo
              - Duplicate
              - NeedsReview
              - NonOrigoInProgress
              - PaymentAllocated
              - Rejected
        status:
          type: string
          enum:
            - Requested
            - NewTransfer
            - FundsSent
            - Complete
            - Cancelled
            - OnHold
            - SubmittedToOrigo
            - NeedsRequestingOnOrigo
            - Duplicate
            - NeedsReview
            - NonOrigoInProgress
            - PaymentAllocated
            - Rejected
        statusUpdatedAt:
          type: string
        user:
          $ref: '#/components/schemas/Customer'
        reference:
          type: string
        referenceNumber:
          type: integer
          format: int32
        finalValue:
          type: number
          format: float
        rejectionReason:
          type: string
          enum:
            - AlreadyTransferred
            - AddressIncorrect
            - NameIncorrect
            - NinoIncorrect
            - PolicyNumberIncorrect
            - NotFound
            - StillContributing
            - ProviderContactedCustomer
            - UnusualReason
        rejectionCustomerResponded:
          type: boolean
        payment:
          $ref: '#/components/schemas/Payment'
    Refund:
      type: object
      required:
        - id
        - createdAt
        - updatedAt
        - penceAmount
        - reason
        - payment
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        penceAmount:
          type: integer
          format: int32
        reason:
          type: string
        payment:
          $ref: '#/components/schemas/Payment'
        user:
          $ref: '#/components/schemas/Customer'
    Payment:
      type: object
      required:
        - id
        - createdAt
        - updatedAt
        - value
        - source
        - completedDate
        - expectation
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        deletedAt:
          type: string
        completedDate:
          type: string
        value:
          type: integer
          format: int32
        source:
          type: string
          enum:
            - TaxReclaim
            - Referral
            - Business
            - Personal
            - Transfer
        customer:
          $ref: '#/components/schemas/Customer'
    PensionProvider:
      type: object
      required:
        - id
        - createdAt
        - updatedAt
        - name
        - address
        - origo
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        name:
          type: string
        address:
          $ref: '#/components/schemas/Address'
        origo:
          type: boolean
        email:
          type: string
    TracingUrlRecord:
      type: object
      required:
        - id
        - createdAt
        - updatedAt
        - recordId
        - order
        - docType
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        recordId:
          type: integer
          format: int32
        order:
          type: integer
          format: int32
        docType:
          type: string
          enum:
            - None
            - Invalid
            - Employer
            - NotFound
            - Deleted
        error:
          type: string
        employer:
          $ref: '#/components/schemas/TracingEmployer'
        normalizedName:
          type: string
        schemeCount:
          type: integer
          format: int32
    TracingEmployer:
      type: object
      required:
        - id
        - createdAt
        - updatedAt
        - name
        - normalizedName
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        urlRecords:
          type: array
          items:
            $ref: '#/components/schemas/TracingUrlRecord'
        recordCount:
          type: integer
          format: int32
        schemeCount:
          type: integer
          format: int32
        name:
          type: string
        normalizedName:
          type: string
        schemes:
          type: array
          items:
            $ref: '#/components/schemas/TracingScheme'
    TracingScheme:
      type: object
      required:
        - id
        - createdAt
        - updatedAt
        - name
        - archived
      properties:
        id:
          type: string
        hash:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        name:
          type: string
        previousNames:
          type: array
          items:
            type: string
        archived:
          type: boolean
        address:
          $ref: '#/components/schemas/TracingAddress'
        employers:
          type: array
          items:
            $ref: '#/components/schemas/TracingEmployer'
    TracingAddress:
      type: object
      required:
        - id
        - createdAt
        - updatedAt
        - hash
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        hash:
          type: string
        address1:
          type: string
        address2:
          type: string
        address3:
          type: string
        address4:
          type: string
        postcode:
          type: string
        country:
          type: string
        phone:
          type: string
        provider:
          $ref: '#/components/schemas/PensionProvider'
        schemeCount:
          type: integer
          format: int32
        schemes:
          type: array
          items:
            $ref: '#/components/schemas/TracingScheme'
    TracingInvalidName:
      type: object
      required:
        - id
        - name
        - normalizedName
      properties:
        id:
          type: string
        name:
          type: string
        normalizedName:
          type: string
        reason:
          type: string
    Beneficiary:
      type: object
      required:
        - id
        - dateSubmitted
        - user
        - firstName
        - lastName
        - relationship
        - address
        - percentage
      properties:
        id:
          type: string
        dateSubmitted:
          type: string
        user:
          $ref: '#/components/schemas/Customer'
        firstName:
          type: string
        lastName:
          type: string
        phone:
          type: string
        relationship:
          type: string
          enum:
            - Other
            - Wife
            - Husband
            - Partner
            - Son
            - Daughter
            - Mother
            - Father
        address:
          $ref: '#/components/schemas/Address'
        percentage:
          type: integer
          format: int32
        notes:
          type: string

    timestamp:
      example: 1995-09-07T10:40:52Z
      format: date-time
      type: string
    date:
      example: 1995-09-07
      format: date
      type: string

    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message

  

  parameters:
    pageNumber: 
      in: query
      name: pageNumber
      required: false
      schema:
        type: integer
        minimum: 0
      description: The number of page
    itemsPerPage:
      in: query
      name: perPage
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 50
        default: 20
      description: The numbers of items to return per page.

  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  examples:

    defaultFields:
      value:
        id: 123
        createdAt: 
          $ref: '#/components/schemas/timestamp/example'
        updatedAt:
          $ref: '#/components/schemas/timestamp/example'


    CustomerInput:
      value:
        title: Mr
        firstName: Stuart
        lastName: Robinson
        dateOfBirth: 1983-10-13
        email: stuart@stuart.cloud
        phoneNumber: '06128527894'
        gender: Male
        citizenship: UK
        nationalInsuranceNumber: JH771270C
        employmentStatus: Employed
        address:
          $ref: '#/components/examples/AddressInput'
        
    Customer:
      value:
        allOf: 
        deactivatedAt: 
          $ref: '#/components/schemas/timestamp/example'
        penId: PEN123
        allOf: 
          $ref: '#/components/examples/CustomerInput'

    AddressInput:
      value:
        streetNumber: 1    
        line1: Long Lane
        postcode: SE1 4PG
        country: UK

    AddressInput

    
  
