openapi: 3.0.0
info:
  title: Example API
  version: 3.0.0
paths: {}
components:
  schemas:
    User:
      type: object
      required:
        - id
        - createdAt
        - updatedAt
        - milestone
        - email
        - privacyAcceptedAt
        - emailConfirmed
        - contributionPaused
        - hasActiveDirectDebitMandate
        - employmentStatus
        - isWorkplace
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        milestone:
          type: string
          enum:
            - Created
            - HasFund
            - HasAcceptedTerms
            - PassedAml
            - Ready
            - PendingActive
            - Active
            - Deactivated
            - Void
        email:
          type: string
        deactivatedAt:
          type: string
        title:
          type: string
          enum:
            - Captain
            - Dr
            - Lady
            - Lieutenant
            - LieutenantCommander
            - Lord
            - Major
            - Master
            - Miss
            - Mr
            - Mrs
            - Ms
            - Mx
            - Professor
            - Reverend
            - Sir
            - WingCommander
        firstName:
          type: string
        middleName:
          type: string
        lastName:
          type: string
        phone:
          type: string
        dateOfBirth:
          type: string
        privacyAcceptedAt:
          type: string
        company:
          $ref: '#/components/schemas/Company'
        referralId:
          type: string
        referredBy:
          type: string
        emailConfirmed:
          type: boolean
        monthlyContribution:
          type: integer
          format: int32
        paymentDay:
          type: integer
          format: int32
        contributionPaused:
          type: boolean
        activeFund:
          $ref: '#/components/schemas/Fund'
        activeFundPenceValuation:
          type: integer
          format: int32
        providerTermsAcceptedAt:
          type: string
        custodianTermsAcceptedAt:
          type: string
        trusteeTermsAcceptedAt:
          type: string
        memberDeclarationAcceptedAt:
          type: string
        directDebitMandateAcceptedAt:
          type: string
        hasActiveDirectDebitMandate:
          type: boolean
        employmentStatus:
          type: string
          enum:
            - CareOver16
            - CareUnder16s
            - Child
            - Education
            - Employed
            - Other
            - Retired
            - SelfEmployed
            - Unemployed
            - Director
        countryOfBirth:
          type: string
        citizenship:
          type: string
        gender:
          type: string
          enum:
            - Male
            - Female
        address:
          type: array
          items:
            $ref: '#/components/schemas/Address'
        nationalInsuranceNumber:
          type: string
        isWorkplace:
          type: boolean
        transfers:
          type: array
          items:
            $ref: '#/components/schemas/Transfer'
        expectations:
          type: array
          items:
            $ref: '#/components/schemas/Expectation'
        payments:
          type: array
          items:
            $ref: '#/components/schemas/Payment'
        taxResidencies:
          type: array
          items:
            $ref: '#/components/schemas/TaxResidency'
        penId:
          type: string
        employments:
          type: array
          items:
            $ref: '#/components/schemas/Employment'
        currentEmployment:
          $ref: '#/components/schemas/Employment'
        beneficiaries:
          type: array
          items:
            $ref: '#/components/schemas/Beneficiary'
    TaxResidency:
      type: object
      required:
        - id
        - createdAt
        - updatedAt
        - currentYearResidencyStatus
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        user:
          $ref: '#/components/schemas/User'
        currentYearResidencyStatus:
          type: string
          enum:
            - ScotResident
            - OtherUKResident
        nextYearForecastResidencyStatus:
          type: string
          enum:
            - ScotResident
            - OtherUKResident
    Fund:
      type: object
      required:
        - id
        - createdAt
        - updatedAt
        - ISIN
        - secclId
        - name
        - description
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        externalName:
          type: string
        group:
          type: string
          enum:
            - Basic
            - Advanced
            - Impact
            - Sustainable
            - Shariah
        ISIN:
          type: string
        secclId:
          type: string
        factSheet:
          type: string
        name:
          type: string
        description:
          type: string
        equity:
          type: integer
          format: int32
    Company:
      type: object
      required:
        - id
        - ownershipVerified
      properties:
        id:
          type: string
        number:
          type: string
        companiesHouseData:
          type: string
        ownershipVerified:
          type: boolean
        companyCategory:
          type: string
        companySubCategory:
          type: string
    Address:
      type: object
      required:
        - id
        - line1
        - postcode
        - country
      properties:
        id:
          type: string
        streetNumber:
          type: string
        line1:
          type: string
        line2:
          type: string
        town:
          type: string
        county:
          type: string
        postcode:
          type: string
        country:
          type: string
    Transfer:
      type: object
      required:
        - id
        - createdAt
        - updatedAt
        - provider
        - policyNumber
        - estimatedAmount
        - previousStatuses
        - status
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        airtableId:
          type: string
        address:
          $ref: '#/components/schemas/Address'
        provider:
          type: string
        pensionProvider:
          $ref: '#/components/schemas/PensionProvider'
        policyNumber:
          type: string
        policyNumberRegexIgnored:
          type: boolean
        customerNumber:
          type: string
        estimatedAmount:
          type: integer
          format: int32
        previousStatuses:
          type: array
          items:
            type: string
            enum:
              - Requested
              - NewTransfer
              - FundsSent
              - Complete
              - Cancelled
              - OnHold
              - SubmittedToOrigo
              - NeedsRequestingOnOrigo
              - Duplicate
              - NeedsReview
              - NonOrigoInProgress
              - PaymentAllocated
              - Rejected
        status:
          type: string
          enum:
            - Requested
            - NewTransfer
            - FundsSent
            - Complete
            - Cancelled
            - OnHold
            - SubmittedToOrigo
            - NeedsRequestingOnOrigo
            - Duplicate
            - NeedsReview
            - NonOrigoInProgress
            - PaymentAllocated
            - Rejected
        statusUpdatedAt:
          type: string
        user:
          $ref: '#/components/schemas/User'
        reference:
          type: string
        referenceNumber:
          type: integer
          format: int32
        finalAmount:
          type: number
          format: float
        rejectionReason:
          type: string
          enum:
            - AlreadyTransferred
            - AddressIncorrect
            - NameIncorrect
            - NinoIncorrect
            - PolicyNumberIncorrect
            - NotFound
            - StillContributing
            - ProviderContactedCustomer
            - UnusualReason
        rejectionCustomerResponded:
          type: boolean
        payment:
          $ref: '#/components/schemas/Payment'
    Refund:
      type: object
      required:
        - id
        - createdAt
        - updatedAt
        - penceAmount
        - reason
        - payment
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        penceAmount:
          type: integer
          format: int32
        reason:
          type: string
        payment:
          $ref: '#/components/schemas/Payment'
        user:
          $ref: '#/components/schemas/User'
    Payment:
      type: object
      required:
        - id
        - createdAt
        - updatedAt
        - penceAmount
        - secclTransactionId
        - contributionSource
        - completedDate
        - expectation
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        deletedAt:
          type: string
        penceAmount:
          type: integer
          format: int32
        secclTransactionId:
          type: string
        contributionSource:
          type: string
          enum:
            - TaxReclaim
            - Referral
            - Business
            - Personal
            - Redress
            - Transfer
            - WorkplacePersonal
            - WorkplaceEmployer
        contributionFrequency:
          type: string
          enum:
            - OneOff
            - Monthly
        completedDate:
          type: string
        expectation:
          $ref: '#/components/schemas/Expectation'
        linkedExpectations:
          type: array
          items:
            $ref: '#/components/schemas/Expectation'
        user:
          $ref: '#/components/schemas/User'
        transfer:
          $ref: '#/components/schemas/Transfer'
    Expectation:
      type: object
      required:
        - id
        - createdAt
        - updatedAt
        - createdDate
        - contributionStatus
        - penceAmount
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        createdDate:
          type: string
        secclTransactionId:
          type: string
        secclTransactionLinkId:
          type: string
        contributionFrequency:
          type: string
          enum:
            - OneOff
            - Monthly
        contributionSource:
          type: string
          enum:
            - TaxReclaim
            - Referral
            - Business
            - Personal
            - Redress
            - Transfer
            - WorkplacePersonal
            - WorkplaceEmployer
        contributionStatus:
          type: string
          enum:
            - Cancelled
            - NotSubmitted
            - Pending
            - Completed
            - Deleted
        paymentMethod:
          type: string
          enum:
            - BankTransfer
            - DirectDebit
            - GoCardless
            - StandingOrder
            - InstantPayment
        penceAmount:
          type: integer
          format: int32
        payment:
          $ref: '#/components/schemas/Payment'
        linkedExpectations:
          type: array
          items:
            $ref: '#/components/schemas/Expectation'
        linkedPayment:
          $ref: '#/components/schemas/Payment'
        user:
          $ref: '#/components/schemas/User'
    Employer:
      type: object
      required:
        - id
        - createdAt
        - updatedAt
        - name
        - externalReference
        - company
        - contributionBasis
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        name:
          type: string
        externalReference:
          type: string
        company:
          $ref: '#/components/schemas/Company'
        phone:
          type: string
        tprCode:
          type: string
        contributionBasis:
          type: string
          enum:
            - BasicPay
            - TotalPay
            - QualifyingEarnings
            - NonContributory
    Employment:
      type: object
      required:
        - id
        - createdAt
        - updatedAt
        - startDate
        - employer
        - workplaceStatus
        - eligible
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        startDate:
          type: string
        endDate:
          type: string
        employer:
          $ref: '#/components/schemas/Employer'
        deferredEndDate:
          type: string
        workplaceStatus:
          type: string
          enum:
            - OptedOut
            - OptedIn
        eligible:
          type: boolean
    PensionProvider:
      type: object
      required:
        - id
        - createdAt
        - updatedAt
        - name
        - address
        - origo
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        name:
          type: string
        address:
          $ref: '#/components/schemas/Address'
        origo:
          type: boolean
        email:
          type: string
    TracingUrlRecord:
      type: object
      required:
        - id
        - createdAt
        - updatedAt
        - recordId
        - order
        - docType
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        recordId:
          type: integer
          format: int32
        order:
          type: integer
          format: int32
        docType:
          type: string
          enum:
            - None
            - Invalid
            - Employer
            - NotFound
            - Deleted
        error:
          type: string
        employer:
          $ref: '#/components/schemas/TracingEmployer'
        normalizedName:
          type: string
        schemeCount:
          type: integer
          format: int32
    TracingEmployer:
      type: object
      required:
        - id
        - createdAt
        - updatedAt
        - name
        - normalizedName
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        urlRecords:
          type: array
          items:
            $ref: '#/components/schemas/TracingUrlRecord'
        recordCount:
          type: integer
          format: int32
        schemeCount:
          type: integer
          format: int32
        name:
          type: string
        normalizedName:
          type: string
        schemes:
          type: array
          items:
            $ref: '#/components/schemas/TracingScheme'
    TracingScheme:
      type: object
      required:
        - id
        - createdAt
        - updatedAt
        - name
        - archived
      properties:
        id:
          type: string
        hash:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        name:
          type: string
        previousNames:
          type: array
          items:
            type: string
        archived:
          type: boolean
        address:
          $ref: '#/components/schemas/TracingAddress'
        employers:
          type: array
          items:
            $ref: '#/components/schemas/TracingEmployer'
    TracingAddress:
      type: object
      required:
        - id
        - createdAt
        - updatedAt
        - hash
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        hash:
          type: string
        address1:
          type: string
        address2:
          type: string
        address3:
          type: string
        address4:
          type: string
        postcode:
          type: string
        country:
          type: string
        phone:
          type: string
        provider:
          $ref: '#/components/schemas/PensionProvider'
        schemeCount:
          type: integer
          format: int32
        schemes:
          type: array
          items:
            $ref: '#/components/schemas/TracingScheme'
    TracingInvalidName:
      type: object
      required:
        - id
        - name
        - normalizedName
      properties:
        id:
          type: string
        name:
          type: string
        normalizedName:
          type: string
        reason:
          type: string
    Beneficiary:
      type: object
      required:
        - id
        - dateSubmitted
        - user
        - firstName
        - lastName
        - relationship
        - address
        - percentage
      properties:
        id:
          type: string
        dateSubmitted:
          type: string
        user:
          $ref: '#/components/schemas/User'
        firstName:
          type: string
        lastName:
          type: string
        phone:
          type: string
        relationship:
          type: string
          enum:
            - Other
            - Wife
            - Husband
            - Partner
            - Son
            - Daughter
            - Mother
            - Father
        address:
          $ref: '#/components/schemas/Address'
        percentage:
          type: integer
          format: int32
        notes:
          type: string
